[package]
name = "axplat-aarch64-common"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
kspin = "0.1"
log = "=0.4.21"
int_ratio = "0.1"
lazyinit = "0.2"
memory_addr = "0.3"
page_table_entry = "0.5"
aarch64-cpu = "10.0"
tock-registers = "0.9"
arm_pl011 = "0.1"
arm_gicv2 = { version = "0.1" }
arm_pl031 = { version = "0.2" }
axhal_cpu = { version = "0.1", path = "../../axhal_cpu" }
axplat = { version = "0.1", path = "../../axplat" }
