[package]
name = "axplat-example" # to be overwritten
version = "0.1.0"       # to be overwritten
edition = "2021"        # to be overwritten

[dependencies]
axconfig-gen-macros = "0.1"
axhal_plat = { git = "https://github.com/arceos-org/axhal_crates" }
